# Please Note:
# - In PHP Versions <= 7.4 MySQL8 is not supported due to lacking pdo support
# Possible values: php54, php56, php71, php72, php73, php74
#    build:
#      context: ./bin/${PHPVERSION}


version: "3"

services:

  web:
    image: schleyk/apache-php:7.3.18
    restart: 'always'
    ports:
      - "80:80"
    links:
      - db
#      - redis
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2

  db:
    image: mariadb:10
    restart: 'always'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme!
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: changeme!

#  redis:
#    image: redis:latest

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db
#    environment:
#      PMA_HOST: db
#    ports:
#      - '8080:80'




